version: 2

sources:
  - name: raw_data
    database: AIRBNB_AUSTIN
    schema: RAW_DATA
    tables:
      - name: LISTINGS
      - name: CALENDAR
      - name: REVIEWS

models:
  - name: stg_listings
    description: Cleansed listing data with standardized fields and pricing
    columns:
      - name: listing_id
        description: Unique ID for each Airbnb listing
        tests:
          - not_null
          - unique
      - name: price_usd
        description: Standardized price in USD
      - name: "neighbourhood"
        description: Neighborhood location of the listing

  - name: stg_calendar
    description: Daily availability and pricing for listings
    columns:
      - name: listing_id
        description: Foreign key to listings
        tests:
          - not_null
      - name: calendar_date
        description: Date of listing availability
        tests:
          - not_null
      - name: is_available
        description: Availability flag (true/false)
      - name: price_usd
        description: standardized nightly price
        tests:
          - positive_value

  - name: stg_reviews
    description: Guest reviews including reviewer info and comments
    columns:
      - name: listing_id
        description: Foreign key to listings
        tests:
          - not_null
      - name: review_date
        description: Date of the review
        tests:
          - not_null

